# Generated by Django 3.1.7 on 2021-03-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
